#!/usr/bin/env bash
# Build a release archive: the plugin, and a PC app that needs no Python.
#
# The SD card half is laid out as the real thing - drag the contents of
# "SD Card" onto the root of the card and every file lands where it belongs,
# with no instructions to misread. The PC half is a PyInstaller one-dir build
# rather than one-file, because one-file re-extracts 200 MB to a temp directory
# on every launch and this is an app people will open and close a lot.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

VERSION="$(cat VERSION)"
NAME="wiiu-stream-v$VERSION"
STAGE="$ROOT/release/$NAME"

echo "==> wiiu-stream $VERSION"

# Single source of truth: the plugin gets it via -D, the app via this module,
# so the two can never disagree about what they are.
cat > pc/_version.py <<EOF
"""Generated by tools/make-release.sh from the VERSION file. Do not edit."""
__version__ = "$VERSION"
EOF

echo "==> plugin"
bash tools/build-plugin.sh >/dev/null
echo "    build/wiiustream.wps  $(stat -c%s build/wiiustream.wps) bytes"

echo "==> PC app"
rm -rf build/dist build/pyi
( cd pc && python -m PyInstaller --noconfirm --clean --windowed \
    --name WiiUStream \
    --distpath ../build/dist --workpath ../build/pyi --specpath ../build \
    --collect-all imgui_bundle \
    --hidden-import audio_out --hidden-import receiver --hidden-import _version \
    --exclude-module PIL --exclude-module yaml \
    --exclude-module tkinter --exclude-module unittest \
    dashboard.py ) >/dev/null 2>&1
echo "    build/dist/WiiUStream  $(du -sm build/dist/WiiUStream | cut -f1) MB"

echo "==> staging"
rm -rf "$STAGE"
mkdir -p "$STAGE/SD Card/wiiu/environments/aroma/plugins"
mkdir -p "$STAGE/PC"

cp build/wiiustream.wps "$STAGE/SD Card/wiiu/environments/aroma/plugins/"
cp -r build/dist/WiiUStream/. "$STAGE/PC/"
cp README.md "$STAGE/DOCUMENTATION.md"

cat > "$STAGE/README.txt" <<EOF
Wii U Stream $VERSION
=====================

Streams your Wii U's picture and sound to this PC over Wi-Fi, with no capture
card, and gives Discord something to share.

Requires Aroma on the console (https://wiiu.hacks.guide). Nothing else.


1. THE CONSOLE
--------------
Copy the CONTENTS of the "SD Card" folder onto the root of your Wii U's SD
card. The plugin will land in:

    wiiu/environments/aroma/plugins/wiiustream.wps

Put the card back and boot into Aroma. There is nothing to configure on the
console - no IP to type, no menu. It sits idle until the PC app asks for a
stream, and costs nothing while idle.


2. THE PC
---------
Run PC\\WiiUStream.exe. Windows may warn about an unsigned app; it is not
signed because signing certificates cost money.

Start a game on the console. The app finds it by broadcast within a second or
two. If your network blocks broadcast (common on mesh systems and guest
networks), type the console's IP into the Console box.


3. INTO DISCORD
---------------
Discord has no address you can stream to, so give its client something it
already understands:

  Screen share - Go Live, choose Application Window, pick "Wii U Stream".
                 Audio is played by the app, so the screen share carries it
                 too. Nothing else to install.

  Webcam       - tick "Virtual camera" (needs OBS Studio installed for its
                 virtual camera driver), then pick it in Discord's settings.


TUNING
------
Start with the Balanced preset. If it is too soft or too choppy, the presets
are measured settings rather than guesses - Smooth is ~30 fps, Sharp is ~18
with more detail.

Leave "Auto scaling" ticked. The console measures its own frame time and
lowers quality, then resolution, to hold the rate you asked for. With it off
it keeps the quality and the frame rate falls instead.

The GamePad source is cheaper for the console than the TV, so it runs faster.

"Audio only" turns capture off entirely - for when you want to watch the
picture on the console itself and only need the sound over here.


IF SOMETHING GOES WRONG
-----------------------
The log pane at the bottom is the console talking. Save log writes it to
captures\\ with the settings that produced it at the top.

See DOCUMENTATION.md for what the numbers mean and how the thing works.
EOF

echo "==> archive"
mkdir -p release
( cd release && rm -f "$NAME.zip" && \
  powershell -NoProfile -Command \
    "Compress-Archive -Path '$NAME' -DestinationPath '$NAME.zip' -Force" )

echo
echo "release/$NAME.zip  $(du -sm "release/$NAME.zip" | cut -f1) MB"
